# Generated by Django 4.2 on 2024-03-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_portfolio_alter_student_major'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='about',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
