# Generated by Django 4.2 on 2024-04-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ended', models.BooleanField()),
                ('about', models.CharField(blank=True, max_length=5000)),
                ('gamelink', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
