# Generated by Django 4.2 on 2024-04-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goteach_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='gamelink',
            new_name='game_link',
        ),
    ]
