# Generated by Django 4.2 on 2024-04-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goteach_app', '0003_class_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='presentation_file',
            field=models.FileField(blank=True, null=True, upload_to='presentations'),
        ),
    ]
